module.exports = {
    env: {
        es6: true,
        browser: true,
        node: true,
    },
    extends: ['eslint:recommended'],
    plugins: [],
    parserOptions: {
        sourceType: 'module',
        ecmaVersion: 2020,
    },
    globals: {
        document: 'readonly',
        navigator: 'readonly',
        window: 'readonly',
    },
    rules: {
        // "eslint": "^7.32.0",

        /* recommended unchange */
        'no-dupe-class-members': ['error'],
        'no-empty-pattern': ['error'],
        'no-extra-semi': ['error'],
        'no-import-assign': ['error'],
        'no-irregular-whitespace': ['error'],
        'no-redeclare': ['error'],
        'no-sparse-arrays': ['error'],

        /* recommended change */
        'no-control-regex': ['off'],
        'no-debugger': ['warn'],
        'no-constant-condition': [
            'error',
            {
                checkLoops: false,
            },
        ],
        'no-unused-vars': [
            'warn',
            {
                args: 'after-used',
            },
        ],

        /* Possible Errors */
        'no-await-in-loop': ['off'],
        'no-console': ['warn', { allow: ['info', 'warn', 'error'] }],
        'no-extra-parens': ['off'],
        'no-loss-of-precision': ['error'],
        'no-promise-executor-return': ['error'],
        'no-template-curly-in-string': ['error'],
        'no-unreachable-loop': ['error'],
        'no-unsafe-optional-chaining': ['error'],
        'no-useless-backreference': ['error'],
        'require-atomic-updates': ['off'],

        /* Best Practices */
        'accessor-pairs': [
            'error',
            {
                setWithoutGet: true,
                getWithoutSet: true,
            },
        ],
        'array-callback-return': ['error'],
        'block-scoped-var': ['error'],
        'class-methods-use-this': ['off'],
        complexity: ['off'],
        'consistent-return': ['error'],
        curly: ['error', 'all'],
        'default-case': ['error'],
        'default-case-last': ['error'],
        'default-param-last': ['off'],
        'dot-location': ['error', 'property'],
        'dot-notation': ['error'],
        eqeqeq: ['error', 'always'],
        'grouped-accessor-pairs': ['error', 'anyOrder'],
        'guard-for-in': ['off'],
        'max-classes-per-file': ['off'],
        'no-alert': ['error'],
        'no-caller': ['error'],
        'no-constructor-return': ['error'],
        'no-div-regex': ['off'],
        'no-else-return': ['off'],
        'no-empty-function': ['off'],
        'no-eq-null': ['error'],
        'no-eval': ['error'],
        'no-extend-native': ['off'],
        'no-extra-bind': ['error'],
        'no-extra-label': ['error'],
        'no-floating-decimal': ['error'],
        'no-implicit-coercion': ['off'],
        'no-implicit-globals': ['error'],
        'no-implied-eval': ['error'],
        'no-invalid-this': ['off'],
        'no-iterator': ['error'],
        'no-labels': ['error'],
        'no-lone-blocks': ['error'],
        'no-loop-func': ['error'],
        'no-magic-numbers': ['off'],
        'no-multi-spaces': ['error'],
        'no-multi-str': ['error'],
        'no-new': ['error'],
        'no-new-func': ['error'],
        'no-new-wrappers': ['error'],
        'no-nonoctal-decimal-escape': ['error'],
        'no-octal-escape': ['error'],
        'no-param-reassign': ['off'],
        'no-proto': ['error'],
        'no-restricted-properties': ['off'],
        'no-return-assign': ['error'],
        'no-return-await': ['off'],
        'no-script-url': ['error'],
        'no-self-compare': ['error'],
        'no-sequences': ['error'],
        'no-throw-literal': ['error'],
        'no-unmodified-loop-condition': ['error'],
        'no-unused-expressions': [
            'error',
            {
                allowShortCircuit: true,
                allowTernary: true,
            },
        ],
        'no-useless-call': ['error'],
        'no-useless-concat': ['error'],
        'no-useless-return': ['error'],
        'no-void': ['error'],
        'no-warning-comments': ['off'],
        'prefer-named-capture-group': ['off'],
        'prefer-promise-reject-errors': ['off'],
        'prefer-regex-literals': ['error'],
        radix: ['error', 'always'],
        'require-await': ['error'],
        'require-unicode-regexp': ['off'],
        'vars-on-top': ['off'],
        'wrap-iife': [
            'error',
            'inside',
            {
                functionPrototypeMethods: true,
            },
        ],
        yoda: ['error', 'never'],

        /* Strict Mode */
        strict: ['off'],

        /* Variables */
        'init-declarations': ['off'],
        'no-label-var': ['error'],
        'no-restricted-globals': ['off'],
        'no-shadow': [
            'error',
            {
                builtinGlobals: true,
                hoist: 'all',
                allow: [
                    'name',
                    'value',
                    'node',
                    'index',
                    'self',
                    'field',
                    'tr',
                    'column',
                    'event',
                    'status',
                    'close',
                    'confirm',
                    'Option',
                ],
            },
        ],
        'no-undef-init': ['off'],
        'no-undefined': ['off'],
        'no-use-before-define': ['error', { functions: false, variables: false }],

        /* Stylistic Issues */
        'array-bracket-newline': ['error', 'consistent'],
        'array-bracket-spacing': ['error', 'never'],
        'array-element-newline': ['off'],
        'block-spacing': ['error', 'always'],
        'brace-style': ['error', '1tbs', { allowSingleLine: true }],
        camelcase: ['off'],
        'capitalized-comments': ['off'],
        'comma-dangle': ['error', 'always-multiline'],
        'comma-spacing': [
            'error',
            {
                before: false,
                after: true,
            },
        ],
        'comma-style': ['error', 'last'],
        'computed-property-spacing': ['error', 'never'],
        'consistent-this': ['error', 'self'],
        'eol-last': ['error', 'always'],
        'func-call-spacing': ['error', 'never'],
        'func-name-matching': ['error', 'always', { includeCommonJSModuleExports: true }],
        'func-names': ['error', 'never'],
        'func-style': ['off'],
        'function-call-argument-newline': ['error', 'consistent'],
        'function-paren-newline': ['error', 'multiline'],
        'id-blacklist': ['off'],
        'id-length': ['off'],
        'id-match': ['off'],
        'implicit-arrow-linebreak': ['error', 'beside'],
        indent: ['error', 4, { SwitchCase: 1 }],
        'jsx-quotes': ['error', 'prefer-double'],
        'key-spacing': [
            'error',
            {
                beforeColon: false,
                afterColon: true,
                mode: 'strict',
            },
        ],
        'keyword-spacing': [
            'error',
            {
                before: true,
                after: true,
            },
        ],
        'line-comment-position': ['off'],
        'linebreak-style': ['error', 'unix'],
        'lines-around-comment': ['error'],
        'lines-between-class-members': ['error', 'always'],
        'max-depth': ['error', 6],
        'max-len': ['off'],
        'max-lines': ['off'],
        'max-lines-per-function': ['off'],
        'max-nested-callbacks': ['error', 5],
        'max-params': ['error', 5],
        'max-statements': ['off'],
        'max-statements-per-line': ['error', { max: 3 }],
        'multiline-comment-style': ['off'],
        'multiline-ternary': ['off'],
        'new-cap': ['error'],
        'new-parens': ['error', 'always'],
        'newline-per-chained-call': ['off'],
        'no-array-constructor': ['error'],
        'no-bitwise': ['off'],
        'no-continue': ['off'],
        'no-inline-comments': ['off'],
        'no-lonely-if': ['off'],
        'no-mixed-operators': [
            'error',
            {
                groups: [
                    // ["+", "-", "*", "/", "%", "**"],
                    ['&', '|', '^', '~', '<<', '>>', '>>>'],
                    ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
                    ['&&', '||'],
                    ['in', 'instanceof'],
                ],
                allowSamePrecedence: true,
            },
        ],
        'no-multi-assign': ['error'],
        'no-multiple-empty-lines': [
            'error',
            {
                max: 3,
                maxEOF: 1,
                maxBOF: 1,
            },
        ],
        'no-negated-condition': ['off'],
        'no-nested-ternary': ['off'],
        'no-new-object': ['error'],
        'no-plusplus': ['off'],
        'no-restricted-syntax': ['off'],
        'no-tabs': ['error'],
        'no-ternary': ['off'],
        'no-trailing-spaces': ['error'],
        'no-underscore-dangle': ['off'],
        'no-unneeded-ternary': ['error'],
        'no-whitespace-before-property': ['error'],
        'nonblock-statement-body-position': ['error'],
        'object-curly-newline': [
            'error',
            {
                consistent: true,
            },
        ],
        'object-curly-spacing': ['error', 'always'],
        'object-property-newline': ['off'],
        'one-var': ['off'],
        'one-var-declaration-per-line': ['off'],
        'operator-assignment': ['error'],
        'operator-linebreak': ['error', 'after'],
        'padded-blocks': ['off'],
        'padding-line-between-statements': ['off'],
        'prefer-exponentiation-operator': ['error'],
        'prefer-object-spread': ['off'],
        'quote-props': [
            'error',
            'as-needed',
            {
                numbers: true,
            },
        ],
        quotes: ['error', 'single'],
        semi: ['error', 'never'],
        'semi-spacing': [
            'error',
            {
                before: false,
                after: true,
            },
        ],
        'semi-style': ['error', 'last'],
        'sort-keys': ['off'],
        'sort-vars': ['off'],
        'space-before-blocks': ['error'],
        'space-before-function-paren': [
            'error',
            {
                anonymous: 'always',
                named: 'never',
                asyncArrow: 'always',
            },
        ],
        'space-in-parens': ['error', 'never'],
        'space-infix-ops': ['error'],
        'space-unary-ops': [
            'error',
            {
                words: true,
                nonwords: false,
            },
        ],
        'spaced-comment': ['error', 'always'],
        'switch-colon-spacing': [
            'error',
            {
                before: false,
                after: true,
            },
        ],
        'template-tag-spacing': ['error', 'never'],
        'unicode-bom': ['error', 'never'],
        'wrap-regex': ['off'],

        /* ECMAScript 6 */
        'arrow-body-style': ['off'],
        'arrow-parens': ['error', 'always'],
        'arrow-spacing': [
            'error',
            {
                before: true,
                after: true,
            },
        ],
        'generator-star-spacing': [
            'error',
            {
                before: true,
                after: true,
            },
        ],
        'no-confusing-arrow': ['error', { allowParens: true }],
        'no-duplicate-imports': ['error', { includeExports: true }],
        'no-restricted-exports': ['off'],
        'no-restricted-imports': ['off'],
        'no-useless-computed-key': ['error'],
        'no-useless-constructor': ['off'],
        'no-useless-rename': ['error'],
        'no-var': ['error'],
        'object-shorthand': ['error', 'always'],
        'prefer-arrow-callback': ['error'],
        'prefer-const': [
            'error',
            {
                destructuring: 'all',
                ignoreReadBeforeAssign: false,
            },
        ],
        'prefer-destructuring': ['off'],
        'prefer-numeric-literals': ['off'],
        'prefer-rest-params': ['error'],
        'prefer-spread': ['error'],
        'prefer-template': ['off'],
        'rest-spread-spacing': ['error', 'never'],
        'sort-imports': ['off'],
        'symbol-description': ['error'],
        'template-curly-spacing': ['error', 'never'],
        'yield-star-spacing': [
            'error',
            {
                before: true,
                after: true,
            },
        ],
    },
}
