// eslint-disable-next-line @typescript-eslint/no-var-requires
const basic = require('../basic/index.js')

const extensionRulesByBasic = {}
const extensionRuleNames = [
    'array-bracket-newline',
    'array-bracket-spacing',
    'arrow-spacing',
    'block-spacing',
    'brace-style',
    'camelcase',
    'comma-dangle',
    'comma-spacing',
    'comma-style',
    'dot-location',
    'dot-notation',
    'eqeqeq',
    'func-call-spacing',
    'key-spacing',
    'keyword-spacing',
    'max-len',
    'no-constant-condition',
    'no-empty-pattern',
    'no-extra-parens',
    'no-irregular-whitespace',
    'no-restricted-syntax',
    'no-sparse-arrays',
    'no-useless-concat',
    'object-curly-newline',
    'object-curly-spacing',
    'object-property-newline',
    'operator-linebreak',
    'prefer-template',
    'space-in-parens',
    'space-infix-ops',
    'space-unary-ops',
    'template-curly-spacing',
]
extensionRuleNames.forEach((ruleName) => {
    extensionRulesByBasic[`vue/${ruleName}`] = basic.rules[ruleName]
})

module.exports = {
    overrides: [
        {
            files: ['*.vue'],
            parser: 'vue-eslint-parser',
            parserOptions: {
                parser: '@typescript-eslint/parser',
            },
        },
    ],
    extends: ['plugin:vue/vue3-recommended', './eslint.ts.js'],
    parserOptions: {
        extraFileExtensions: ['.vue'],
    },
    rules: {
        // "eslint-plugin-vue": "^7.16.0",

        /* recommended change */
        'vue/html-self-closing': ['off'],
        'vue/no-v-html': ['off'],
        'vue/no-mutating-props': ['off'],
        'vue/attribute-hyphenation': ['error', 'never'],
        'vue/html-indent': [
            'error',
            4,
            {
                attribute: 1,
                baseIndent: 1,
                closeBracket: 0,
                alignAttributesVertically: true,
                ignores: [],
            },
        ],

        /* Uncategorized */
        'vue/block-lang': [
            'error',
            {
                template: { allowNoLang: true },
                script: { lang: 'ts' },
                style: { lang: 'less' },
            },
        ],
        'vue/block-tag-newline': ['off'],
        'vue/component-name-in-template-casing': [
            'error',
            'PascalCase',
            {
                registeredComponentsOnly: false,
            },
        ],
        'vue/custom-event-name-casing': ['error', 'kebab-case'],
        'vue/html-button-has-type': ['off'],
        'vue/html-comment-content-newline': ['off'],
        'vue/html-comment-content-spacing': ['error', 'always'],
        'vue/html-comment-indent': ['error', 2],
        'vue/match-component-file-name': [
            'error',
            {
                extensions: ['vue', 'jsx', 'tsx'],
                shouldMatchCase: true,
            },
        ],
        'vue/new-line-between-multi-line-property': ['off'],
        'vue/next-tick-style': ['off'],
        'vue/no-bare-strings-in-template': ['off'],
        'vue/no-boolean-default': ['off'],
        'vue/no-deprecated-v-is': ['error'],
        'vue/no-duplicate-attr-inheritance': ['error'],
        'vue/no-empty-component-block': ['off'],
        'vue/no-export-in-script-setup': ['off'],
        'vue/no-invalid-model-keys': ['error'],
        'vue/no-multiple-objects-in-class': ['error'],
        'vue/no-potential-component-option-typo': ['off'],
        'vue/no-reserved-component-names': ['error', { disallowVue3BuiltInComponents: true }],
        'vue/no-restricted-block': ['off'],
        'vue/no-restricted-call-after-await': ['off'],
        'vue/no-restricted-component-options': [
            'error',
            'data',
            'computed',
            'methods',
            'watch',
            'beforeCreate',
            'created',
            'beforeMount',
            'mounted',
            'beforeUpdate',
            'updated',
            'activated',
            'deactivated',
            'beforeUnmount',
            'unmounted',
            'errorCaptured',
            'renderTracked',
            'renderTriggered',
            'mixins',
            'extends',
            'provide',
            'inject',
            'delimiters',
        ],
        'vue/no-restricted-custom-event': ['off'],
        'vue/no-restricted-props': ['off'],
        'vue/no-restricted-static-attribute': ['off'],
        'vue/no-restricted-v-bind': ['off'],
        'vue/no-static-inline-styles': ['off'],
        'vue/no-template-target-blank': ['error'],
        'vue/no-this-in-before-route-enter': ['error'],
        'vue/no-unregistered-components': ['off'],
        'vue/no-unsupported-features': ['off'],
        'vue/no-unused-properties': ['error', { groups: ['props', 'setup'], ignorePublicMembers: true }],
        'vue/no-unused-refs': ['error'],
        'vue/no-use-computed-property-like-method': ['error'],
        'vue/no-useless-mustaches': ['off'],
        'vue/no-useless-v-bind': ['off'],
        'vue/padding-line-between-blocks': ['error', 'always'],
        'vue/require-direct-export': ['off'],
        'vue/require-emit-validator': ['error'],
        'vue/require-expose': ['off'],
        'vue/require-name-property': ['off'],
        'vue/script-indent': ['error', 4],
        'vue/sort-keys': ['off'],
        'vue/static-class-names-order': ['off'],
        'vue/v-for-delimiter-style': ['off'],
        'vue/v-on-event-hyphenation': ['error', 'always', { autofix: true }],
        'vue/v-on-function-call': ['off'],
        'vue/valid-define-emits': ['off'],
        'vue/valid-define-props': ['off'],
        'vue/valid-next-tick': ['error'],
        'vue/valid-v-memo': ['error'],

        /* Extension Rules */
        ...extensionRulesByBasic,
    },
}
